### ISSUE TITLE
Sorry, I started one a few weeks ago.

### ISSUE THREAD

**Issue by tomByrer** [irazasyed/awesome-cloudflare#1]
https://github.com/tomByrer/awesome-cloudflare-workers/

I have an Airtable with more links than the ReadMe also; I could give you access to that & my build script?

**Comment by irazasyed** [comment]
Hey @tomByrer!

Thanks for opening this ticket.

Wow, I never came across your repo before (I did in fact research before creating this one), But my search queries were limited to "awesome" and "cloudflare" terms, perhaps that's why it didn't show up.

Anyway, It looks great. Good job on compiling it. But it looks like, it's limited to workers (at least that's what it implies from my quick glance) whereas this repo is a broader list of awesome things for Cloudflare including workers as part of it.

I think a better approach for this would be to merge your list with mine and reorganize the Workers section or exchange links for further expansion of both lists (But the latter might simply end up with a lot of duplicates I suppose).

I'd be happy to add you as the collaborator as well.

Also, Please note my license is different from yours.

Let me know your thoughts on this. Thanks!

**Comment by tomByrer** [comment]
Correct, I'm only focused on Workers, since I was looking for help, but it was hard to find.
Other CloudFlare services are net, I might even use their video, but out of scope for my list.

I'm trying to keep the 'awesome' list limited, to around 50 links.  So if a better project or article is released, it will bump out an outdated one.   I think it would be bad to keep stale links.

Right now my workflow is:
 1) AirTable for database & entry
 2) export to CVS
 3) run JavaScript locally to rebuild the MarkDown
  4) push the MD & CVS files to GitHub.

My long-range goal is to have a website for ALL my collected links (100 vs 50 in the MarkDown), so people can filter down to what they're looking for.

I'm open to merging into yours, but since I have a master database of all the links, I'll have to be in charge of the Workers section.  Though you or anyone suggesting more links would be great.  Then you can focus on the non-Worker Cloudflare stuff?

edit: if you email me your email, I can add you to my AirTable.

**Comment by irazasyed** [comment]
Why would you use AirTable and go through so much of a hassle? People can just send a PR with the link and the same could then be parsed/exported if needed for whatever reasons.

And what do you exactly mean by "in-charge"?

If it's something like you'd be the one handling that section fully and I can't manage it, then I don't think that is feasible with me (or anyone). It has to be open for all collaborators to make changes (ofc within the defined criteria as long as they meet) and everyone else to suggest/send PRs.

Sure we might have some preference for a specific section but not letting others make changes would not really be helpful to anyone. I hope you see my point?

The goal of this list is to find and curate useful and "awesome" things related to CF. So there could be links that you might come across which is useful and fits the criteria and could add it or I could come across some worker recipe and add it too.

I do agree with removing stale links from time to time to keep the list fresh and up to date with relevant content but we obviously can't put a number and limit the list to 50 or 100 links since there are so many links.

Further, what's your goal with the site if I may ask? Are you planning to monetize the content? Please let me know.

**Comment by tomByrer** [comment]
Anyone can [submit a link here](https://airtable.com/shryEZ28iLgjBbTCE)

It will be added forever to the database (unless it is a duplicate, broken, risky, etc).  There will be somebody who can find a use for it.

Since only 'awesome` links may be in the readme, but many are not that good, I curate in the database, not by accepting or rejecting PRs like most folks.  Right now I have 100 links that is too much for such a narrow scope.  

The website is to list ALL links, but add filtering which a README can not do.  I don't plan to monetize it at this moment, but I do have a slightly tighter CC incase someone does, I'll at least get credit.

**Comment by irazasyed** [comment]
Alright, That makes sense!

So regarding the website and license, since mine is different. How can we merge it then?

We obviously can't have two separate licenses and generally speaking, most of the awesome lists don't demand credits since it's merely a list of links curated by everyone (author/contributors) and giving credit to one person isn't really fair nor the author is adding any copyrighted work.

That kinda license may make sense to maybe your own worker script, site, etc. but a list I don't think so.

Let me know your thoughts on the license issue.

**Comment by sindresorhus** [comment]
Note that Awesome lists should not be generated and contributions should be in the form of PRs to the Markdown readme.

**Comment by irazasyed** [comment]
@sindresorhus Thanks for the comment. I'll keep that in mind. We don't generate it.
